version: '3'

services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"  # Adjust port as needed for your application
    command: npm run dev --
    environment:
      - NODE_ENV=development