services:
  suppl-ai:
    container_name: suppl-ai
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev --"
    environment:
      - NODE_ENV=development
