services:
  suppl-ai-svelte:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"  
    command: npm run dev -- # da cambiare in produzione
    environment:
      - NODE_ENV=development